baseURL = "https://rctilford.github.io/tilford_tech_support/"
languageCode = "en-us"
title = "Tilford Tech Support"

# Theme Config
theme = "hugo-saasify-theme"

# Enable syntax highlighting
pygmentsCodeFences = true
pygmentsUseClasses = true

# Enable emoji support
enableEmoji = true

# Enable Git info for lastmod
enableGitInfo = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

# Enable taxonomies
[taxonomies]
  category = 'categories'
  tag = 'tags'

# Pagination
paginate = 6
paginatePath = "page"

[params]
  description = ""
  author = "Rhys Tilford"
  logo = "/images/logo.svg"
  # Google Analytics ID (e.g., "G-XXXXXXXXXX")
  # googleAnalytics = "G-XXXXXXXXXX"
  
  # Global CTA Configuration
  [params.cta]
    enable = true
    title = "Ready to get your tech in tip top shape?"
    description = "Get your tech in tune with your needs."
    gradient_from = "#2563eb"  # Indigo-600
    gradient_to = "#7c3aed"    # Purple-600
    gradient_angle = 30
    [params.cta.primary_button]
      text = "Pricing"
      url = "/pricing"
    [params.cta.secondary_button]
      text = "Book Consult"
      url = "/book-consult"
  
  # Social Media Links
  [params.social]
    linkedin = "https://linkedin.com/in/rhystilford"
    facebook = "https://facebook.com/rctilford"
    github = "https://github.com/rctilford"
  
  # Footer Configuration
  [params.footer]
    column_1_title = "Services"
    column_2_title = "COMPANY"
    column_3_title = "LEGAL"
  
  [params.header]
    # Header background and border styles (optional)
    background = "bg-white/80 backdrop-blur-sm"
    border = "border-b border-gray-100"
    
    # Logo configuration
    [params.header.logo]
      src = "/images/logo.svg"
    
    # Menu configuration
    [params.header.menu]
      spacing = "space-x-8"
      
      # Dropdown menu configuration
      [params.header.menu.dropdown]
        width = "w-72"
        container_padding = "py-6"
        item_padding = "px-8 py-3"
        background = "bg-white"
        border = "border border-gray-100"
        shadow = "shadow-xl"
        radius = "rounded-lg"
        text_color = "text-gray-700"
        hover_background = "hover:bg-gray-50"
        text_size = "text-sm"
    
    # Button configuration
    [params.header.buttons]
      # Sign In button
      [params.header.buttons.signIn]
        text = "Sign in"
        url = "/signin"
      
      # Get Started button
      [params.header.buttons.getStarted]
        text = "Book Consult"
        url = "/book-consult"

  # Blog configuration
  [params.blog]
    enable = true
    title = "Latest Articles"
    subtitle = "Learn more about web development and best practices"
    
    # Blog CTA configuration
    [params.blog.cta]
      enable = true  # Enable/disable CTA in blog posts
    
    # Sidebar configuration
    [params.blog.sidebar]
      # Recent articles section
      [params.blog.sidebar.recent]
        enable = true
        title = "Recent Articles"
        count = 5
      
      # Categories section
      [params.blog.sidebar.categories]
        enable = true
        title = "Categories"
      
      # Tags section
      [params.blog.sidebar.tags]
        enable = true
        title = "Popular Tags"
        count = 20

      # Subscribe form section
      [params.blog.sidebar.subscribe]
        enable = true
        title = "Subscribe to Newsletter"
        description = "Get the latest posts delivered right to your inbox"
        action = "https://formspree.io/f/mgvzazed"
        emailName = "email"
        buttonText = "Subscribe"
        placeholder = "Enter your email"
        disclaimer = "We respect your privacy. Unsubscribe at any time."

[module]
  [module.hugoVersion]
    extended = true
    min = "0.80.0"

[build]
  writeStats = true

[build.buildStats]
  enable = true

[security.funcs]
  getenv = ['^HUGO_', '^CI$']

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    codeFences = true
    guessSyntax = true
    lineNumbersInTable = true
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 2

# Navigation Menu
[menu]
  [[menu.main]]
    name = "Services"
    weight = 1
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "Cassette Digitization", url = "/features/performance/" },
        { name = "Virus Removal and OS Recovery", url = "/features/design-system/" },
        { name = "File Conversion", url = "/features/developer-experience/" }
      ]
  [[menu.main]]
    name = "Pricing"
    url = "/pricing"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 3
  [[menu.main]]
    name = "Company"
    weight = 4
    [menu.main.params]
      has_submenu = true
      submenu = [
        { name = "About Me", url = "/company/" },
        { name = "Contact Me", url = "/careers/" }
      ]

  # Footer Column 1 Menu
  [[menu.footer_column_1]]
    name = "Cassette Digitization"
    url = "/features/performance/"
    weight = 1
  [[menu.footer_column_1]]
    name = "Virus Removal and OS Recovery"
    url = "/features/design-system/"
    weight = 2
  [[menu.footer_column_1]]
    name = "File Conversion"
    url = "/features/developer-experience/"
    weight = 3

  # Footer Column 2 Menu
  [[menu.footer_column_2]]
    name = "Blog"
    url = "/blog"
    weight = 1
  [[menu.footer_column_2]]
    name = "About Us"
    url = "/company"
    weight = 2
  [[menu.footer_column_2]]
    name = "Get In Touch"
    url = "/careers"
    weight = 3

  # Footer Column 3 Menu
  [[menu.footer_column_3]]
    name = "License"
    url = "/license"
    weight = 1
  [[menu.footer_column_3]]
    name = "Privacy Policy"
    url = "/privacy"
    weight = 2
